### ISSUE TITLE
Apparently incompatible with IDA 7.4

### ISSUE THREAD

**Issue by minerva** [argp/iBoot64helper#10]
When trying to load a securerom with 7.4 IDA reports the following error message:

```
TypeError: in method 'find_imm', argument 1 of type 'ea_t'
```
in `find_img4decodeinit [iBoot64helper.py: line 143]`
```
ea, meh = ida_search.find_imm(cur_ea, ida_search.SEARCH_DOWN, 0x494D)
```

**Comment by VV4rlock** [comment]
apply this patch #11

**Comment by itinerant-fox** [comment]
@Vlad9n Getting the same even after the patch. Running on iBoot.n61 from iPhone 6 - 10.1.1  in IDA Pro 7.5

**Comment by argp** [comment]
Latest commit should fix this issue:

https://github.com/argp/iBoot64helper/commit/cddedd3f9e021ae5b90d65862e33154d50ce06f6

**Comment by itinerant-fox** [comment]
> 
> 
> Latest commit should fix this issue:
> 
> [cddedd3](https://github.com/argp/iBoot64helper/commit/cddedd3f9e021ae5b90d65862e33154d50ce06f6)

Getting Error:
local variable 'ea' referenced before assignment

File "iBoot64helper.py", line 744, in load_file
    find_interesting(segment_start, segment_end)
  File "iBoot64helper.py", line 605, in find_interesting
    i4d_ea = find_img4decodeinit(base_ea)
  File "iBoot64helper.py", line 194, in find_img4decodeinit
    cur_ea = ea + 4

This fixed it:

 if ea_list[0] == ida_idaapi.BADADDR:
             ea_list = ida_search.find_imm(cur_ea, ida_search.SEARCH_DOWN, 0x494D0000)
             if ea_list[0] == ida_idaapi.BADADDR:
                 break

**Comment by argp** [comment]
Fixed this properly:

https://github.com/argp/iBoot64helper/commit/10bb28e73e6bb10ebc99db6503e06fb249fdc857

**Comment by itinerant-fox** [comment]
It shows the following and seems to be going on a loop. No error message. 

  0. Creating a new segment  (0000000000000000-0000000000099000) ... ... OK
[+] Marked as code
[+] Rebasing to address 0x830000000
Rebasing program to 0x0000000830000000...
[+] Searching and defining functions
[+] Identified 0 new functions
[+] Looking for interesting functions
	[-] _macho_valid = not found
	[-] _loaded_kernelcache = not found
	[-] _load_kernelcache = not found
	[+] _panic = 0x83000ff1c
	[+] _do_go = 0x83000237c
	[+] _do_printf = 0x8300251a0
	[-] _image4_validate_property_callback_interposer = not found
	[-] _image4_load = not found
	[-] _image4_validate_property_callback = not found
	[-] _image4_validate_property_callback_interposer_ptr = not found
	[+] _record_memory_range = 0x83000c8a4

Showing scanning at the status bar : from 0x0000000830000008 to 0x0000000830040008 and repeating infinitely.. 

When I press the Cancel button, it continues with

        [+] _Img4DecodeInit = 0x83003130c
	[-] _stack_chk_fail = not found
	[-] _aes_crypto_cmd = not found
	[+] _UpdateDeviceTree = 0x83000aa68
	[-] _macho_load = not found
	[+] _load_kernelcache_object = 0x83000b9e4
	[-] _pmgr_binning_mode_get_value = not found
	[+] _image4_get_partial = 0x830009314
	[+] _main_task = 0x830002644
	[-] _target_early_init = not found
	[+] _boot_check_panic = 0x830001970
	[+] _platform_early_init = 0x83000d0b4
	[-] _chipid_get_chip_revision = not found
	[+] _platform_init_display = 0x83000d24c
	[+] _env_get_uint = 0x830022924
	[+] _env_get_etc = 0x83002282c
	[+] _putchar = 0x830025cac
[+] Identified as a SecureROM image

And all is well...

**Comment by argp** [comment]
What image are you trying it on? I am only testing latest iBoot images (6603.x or newer) myself.

**Comment by argp** [comment]
What binary are you testing with? I am mostly working with new ones (6603.x or newer) myself.

**Comment by itinerant-fox** [comment]
Old ones...  3406.x

**Comment by argp** [comment]
Okay, I'll do some tests on those as well.

**Comment by itinerant-fox** [comment]
Thank you :)

**Comment by argp** [comment]
Latest commit should fix it, but I don't have an old image handy right now to test.
