### ISSUE TITLE
script does not work for iPhone 7 iBoot

### ISSUE THREAD

**Issue by matteyeux** [argp/iBoot64helper#2]
I got an issue while trying to get loading address for `iBoot.d11.RELEASE.im4p` which is iOS 11b6 iBoot for iPhone 7+
Scripts runs for few minutes but nothing happens, until I cancel it. Than I have this error message
![capture d ecran 893](https://user-images.githubusercontent.com/8758978/29628060-99dd31c0-8834-11e7-848c-c7b2f71bdeb0.png)

**Comment by argp** [comment]
You need to decrypt the iBoot im4p file first.

**Comment by matteyeux** [comment]
Well of course I decrypted it

**Comment by argp** [comment]
Just tried it, works fine. Decrypt the iBoot image, load it to IDA, set the processor type to ARM, and when prompted select 64-bit disassembly. Then run the script from IDA.

![iboot-4076 1 43-7p_d11_11b6](https://user-images.githubusercontent.com/145419/29664193-52c0cec0-88d7-11e7-9289-da8e8ba76dd3.png)

**Comment by matteyeux** [comment]
What do you mean, "select 64-bit disassembly" ? 
I may have missed it

**Comment by argp** [comment]
![64](https://user-images.githubusercontent.com/145419/29665314-38073790-88dc-11e7-9a74-faa792f64855.png)

**Comment by matteyeux** [comment]
I don't have any window asking for this
Anyway I assume it is not an issue related with your script

**Comment by argp** [comment]
You probably haven't decrypt it correctly.

**Comment by matteyeux** [comment]
Ok sorry I made a mistake by downloading the wrong ota file, it was the wrong iBoot, your script is working fine (but you may already know it)
